services:
  authelia-redis:
    image: redis:7.4-alpine
    container_name: authelia-redis
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "${REDIS_PASSWORD}"]
    restart: unless-stopped
    volumes:
      - ./redis-data:/data
    networks: [authelia]
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "PING"]
      interval: 10s
      timeout: 3s
      retries: 10

  authelia:
    image: authelia/authelia:latest
    container_name: authelia
    restart: unless-stopped
    depends_on:
      authelia-redis:
        condition: service_healthy
    ports:
      - "9091:9091"
    environment:
      TZ: ${TZ}
    volumes:
      - ./config:/config
      - ./data:/config/data  
    networks: [authelia]
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://127.0.0.1:9091/api/health"]
      interval: 10s
      timeout: 3s
      retries: 10

networks:
  authelia:
    driver: bridge
