services:
  netbootxyz:
    image: ghcr.io/netbootxyz/netbootxyz:latest
    platform: linux/amd64
    container_name: netbootxyz
    restart: unless-stopped
    environment:
      WEB_APP_PORT: "3000"      # web UI
      NGINX_PORT: "80"          # serves mirrored assets
      # MENU_VERSION: "2.0.84"  # optional pin (omit to track latest)
    ports:
      - "3000:3000"             # web UI
      - "69:69/udp"             # TFTP
      - "8080:80"               # local asset mirror
    volumes:
      - ./config:/config
      - ./assets:/assets
