# yamllint disable rule:comments-indentation
---
###############################################################################
#                           Authelia Configuration                            #
###############################################################################

theme: dark

# Use the newer location for the JWT secret used by password resets.
identity_validation:
  reset_password:
    jwt_secret: 9a1099c6d968fa1ef2b2f94be3018f2be0f068c7696dc9df19c1eb4d555c781b

# Keep redirects within your cookie scope to avoid warnings.
default_redirection_url: https://auth.gossman.cloud/

server:
  # Replace deprecated host/port/path with address + endpoints/buffers.
  address: tcp://0.0.0.0:9091/
  endpoints:
    enable_pprof: false
    enable_expvars: false
  buffers:
    read: 4096
    write: 4096
  disable_healthcheck: false
  tls:
    key: ""
    certificate: ""

log:
  level: debug

totp:
  issuer: gossman.cloud
  period: 30
  skew: 1

authentication_backend:
  # Replaces authentication_backend.disable_reset_password
  password_reset:
    disable: false
  refresh_interval: 5m
  file:
    path: /config/users_database.yml
    password:
      algorithm: argon2id
      iterations: 1
      key_length: 32
      salt_length: 16
      memory: 1024
      parallelism: 8

access_control:
  default_policy: deny
  rules:
    - domain:
        - "auth.gossman.cloud"
      policy: bypass

    - domain: "jarvis.gossman.cloud"
      policy: one_factor

    - domain: "imch.gossman.cloud"
      policy: one_factor

    - domain: "sub2.gossman.cloud"
      policy: one_factor

session:
  name: authelia_session
  same_site: lax
  secret: itsmysecret
  expiration: 1h
  inactivity: 5m
  remember_me: true

  # New multi-domain cookie configuration replaces the deprecated single 'domain' option.
  cookies:
    - domain: gossman.cloud
      # Optional per-cookie override; global default_redirection_url already matches scope.
      default_redirection_url: https://auth.gossman.cloud/

  redis:
    host: authelia-redis
    port: 6379
    password: itsmysecret        # must match REDIS_PASSWORD in your .env
    database_index: 0
    maximum_active_connections: 10
    minimum_idle_connections: 0

regulation:
  max_retries: 3
  find_time: 10m
  ban_time: 12h

storage:
  local:
    # Inside the container; bind-mount host ./data -> /config/data in docker-compose.
    path: /config/data/db.sqlite3
  encryption_key: ed428480d7b22d87a4fa540461263d6ab8e2495439672cbb316a40e7a55966d3

notifier:
  disable_startup_check: true
  smtp:
    # New consolidated address key replaces host/port.
    address: submission://smtp.gmail.com:587
    username: youremail@gmail.com
    password: Y0uRp@55W0rD!
    sender: youremail@gmail.com
    identifier: localhost
    subject: "[Authelia] {title}"
    startup_check_address: youremail@gmail.com
    disable_require_tls: false
    disable_html_emails: false
    tls:
      skip_verify: false
      minimum_version: TLS1.2
...
