services:
  glance:
    image: glanceapp/glance                       # Uses the official Glance Docker image.
    container_name: glance                        # Assigns a custom container name for easy management.
    volumes:
      - ./glance.yml:/app/glance.yml              # Mounts the glance.yml configuration file.
      - /etc/timezone:/etc/timezone:ro            # Ensures container timezone sync.
      - /etc/localtime:/etc/localtime:ro          # Ensures container localtime sync.
    ports:
      - 8280:8080                                 # Exposes Glance on port 8280.
    restart: unless-stopped   
